### ISSUE TITLE
Script breaks CC bank

### ISSUE THREAD

**Issue by Clovis5119** [abbydiode/FL-Studio-Arturia-Keystep-37-Script#1]
Hey, found your script through the FL Studio forum and it works pretty well!

There's an issue with it though: when the script is active, FL Studio does not register any of the controls from the Keystep 37's CC bank. I think the script is telling FLS the event has been handled even if it hasn't been, as the script is only catching transport control changes and then sending out event.handled = True. Just my guess from peeking at the code though, as I'm not very familiar with CC scripting.

**Comment by abigailwillow** [comment]
Hi, I unfortunately don't currently have the capacity to develop and test this script right now, but I've just released an update to the script that I believe would fix this issue. Please let me know!

**Comment by Clovis5119** [comment]
Hi Abigail, seems to work perfectly now! Thanks!
